apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: AvailabilityTarget
metadata:
  name: mbentley-at1
  namespace: default
spec:
  affinity:
    clusterAffinity:
      clusterSelectorTerms:
        - matchExpressions:
            - key: tmc.cloud.vmware.com/creator
              operator: In
              values:
                - mbentley
            - key: mbentley-env
              operator: In
              values:
                - at1
    clusterAntiAffinity:
      clusterSelectorTerms: []
  description: mbentley-at1
